### ISSUE TITLE
feature: Video og meta tags

### ISSUE THREAD

**Issue by smrrazavian** [aasaam/url-info#16]
Some new og meta tags have been added in some video news (e.g: [this page](https://www.rokna.net/video/%D8%A8%D8%AE%D8%B4-%D9%86%D9%85%D8%A7%D9%87%D9%86%DA%AF-224/976371-%D8%B1%DB%8C%D9%84%DA%A9%D8%B3-%DA%A9%D9%86%DB%8C%D8%AF-%D9%86%D9%85%D8%A7%D9%87%D9%86%DA%AF-%D8%A8%DB%8C-%DA%A9%D9%84%D8%A7%D9%85-%D8%A2%D8%B1%D8%A7%D9%85%D8%B4-%D8%A8%D8%AE%D8%B4-%D9%81%DB%8C%D9%84%D9%85)).

new tags are:

```html
    <meta property="og:video" content="https://mcdn.rokna.net/f/18df9091cec_e52dbc/EDITED_PATH.mp4">
    <meta property="og:video:url" content="https://mcdn.rokna.net/player/18df9091cec_e52dbc">
    <meta property="og:video:secure_url" content="https://mcdn.rokna.net/player/18df9091cec_e52dbc">
    <meta property="og:video:type" content="video/mp4">
    <meta property="og:video:width" content="1280">
    <meta property="og:video:height" content="720">
    <meta property="og:video:duration" content="114">
```

Could you please provide these meta tags in your service?

**Comment by mhf-ir** [comment]
implemented with audio
